# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(default='male', max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
