# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinformation', '0002_auto_20161123_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
