# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinformation', '0003_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
